src/Entity/ComicCover.php
<?php

namespace App\Entity;

use App\Repository\ComicCoverRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Uid\Ulid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ComicCoverRepository::class)]
#[ORM\Table(name: 'comic_cover')]
#[ORM\UniqueConstraint(columns: ['comic_id', 'image_id'])]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
class ComicCover
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Serializer\Groups(['comic', 'comicCover'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    #[Serializer\Groups(['comic', 'comicCover'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'covers')]
    #[ORM\JoinColumn(name: 'comic_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Comic $comic = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'image_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Image $image = null;

    #[ORM\PrePersist]
    public function onPrePersist(PrePersistEventArgs $args)
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(PreUpdateEventArgs $args)
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getComic(): ?Comic
    {
        return $this->comic;
    }

    #[Serializer\Groups(['comicCover'])]
    public function getComicCode(): ?string
    {
        if ($this->comic == null) {
            return null;
        }

        return $this->comic->getCode();
    }

    public function setComic(?Comic $comic): static
    {
        $this->comic = $comic;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    #[Serializer\Groups(['comic', 'comicCover'])]
    public function getImageULID(): ?Ulid
    {
        if ($this->image == null) {
            return null;
        }

        return $this->image->getUlid();
    }

    public function setImage(?Image $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Entity/ComicExternal.php
<?php

namespace App\Entity;

use App\Repository\ComicExternalRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ComicExternalRepository::class)]
#[ORM\Table(name: 'comic_external')]
#[ORM\UniqueConstraint(columns: ['comic_id', 'link_id'])]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
class ComicExternal
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Serializer\Groups(['comic', 'comicExternal'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    #[Serializer\Groups(['comic', 'comicExternal'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'externals')]
    #[ORM\JoinColumn(name: 'comic_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Comic $comic = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'link_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Link $link = null;

    #[ORM\Column(nullable: true)]
    #[Serializer\Groups(['comic', 'comicExternal'])]
    private ?bool $isOfficial = null;

    #[ORM\Column(nullable: true)]
    #[Serializer\Groups(['comic', 'comicExternal'])]
    private ?bool $isCommunity = null;

    #[ORM\PrePersist]
    public function onPrePersist(PrePersistEventArgs $args)
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(PreUpdateEventArgs $args)
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getComic(): ?Comic
    {
        return $this->comic;
    }

    #[Serializer\Groups(['comicExternal'])]
    public function getComicCode(): ?string
    {
        if ($this->comic == null) {
            return null;
        }

        return $this->comic->getCode();
    }

    public function setComic(?Comic $comic): static
    {
        $this->comic = $comic;

        return $this;
    }

    public function getLink(): ?Link
    {
        return $this->link;
    }

    #[Serializer\Groups(['comic', 'comicExternal'])]
    public function getLinkWebsiteHost(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getWebsiteHost();
    }

    #[Serializer\Groups(['comic', 'comicExternal'])]
    public function getLinkWebsiteName(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getWebsiteName();
    }

    #[Serializer\Groups(['comic', 'comicExternal'])]
    public function getLinkRelativeReference(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getRelativeReference();
    }

    public function setLink(?Link $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function isOfficial(): ?bool
    {
        return $this->isOfficial;
    }

    public function setOfficial(?bool $isOfficial): static
    {
        $this->isOfficial = $isOfficial;

        return $this;
    }

    public function isCommunity(): ?bool
    {
        return $this->isCommunity;
    }

    public function setCommunity(?bool $isCommunity): static
    {
        $this->isCommunity = $isCommunity;

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Uid\Ulid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
#[ORM\Table(name: 'image')]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Serializer\Groups(['image'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    #[Serializer\Groups(['image'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(type: 'ulid', unique: true)]
    #[Serializer\Groups(['image'])]
    private ?Ulid $ulid = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'link_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Link $link = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(allowNull: true), Assert\Length(min: 1, max: 255)]
    #[Serializer\Groups(['image'])]
    private ?string $alternativeText = null;

    #[ORM\PrePersist]
    public function onPrePersist(PrePersistEventArgs $args)
    {
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setUlid(new Ulid());
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(PreUpdateEventArgs $args)
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUlid(): ?Ulid
    {
        return $this->ulid;
    }

    public function setUlid(Ulid $ulid): static
    {
        $this->ulid = $ulid;

        return $this;
    }

    public function getLink(): ?Link
    {
        return $this->link;
    }

    #[Serializer\Groups(['image'])]
    public function getLinkWebsiteHost(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getWebsiteHost();
    }

    #[Serializer\Groups(['image'])]
    public function getLinkRelativeReference(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getRelativeReference();
    }

    public function setLink(?Link $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getAlternativeText(): ?string
    {
        return $this->alternativeText;
    }

    public function setAlternativeText(?string $alternativeText): static
    {
        $this->alternativeText = $alternativeText;

        return $this;
    }
}

src/Controller/ComicController.php
<?php

namespace App\Controller;

use App\Model\OrderByDto;
use App\Repository\ComicRepository;
use App\Service\ComicKingApp;
use App\Util\UrlQuery;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute as HttpKernel;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Attribute as Routing;

#[Routing\Route('/comics', name: 'app_comic_')]
class ComicController extends AbstractController
{
    public function __construct(
        private readonly ComicRepository $comicRepository,
        private readonly ComicKingApp $comicKingApp
    ) {}

    #[Routing\Route('/', name: 'index')]
    #[HttpKernel\Cache(public: true, maxage: 1800, mustRevalidate: true)]
    public function index(
        Request $request,
        #[HttpKernel\MapQueryParameter(options: ['min_range' => 1])] int $page = 1,
        #[HttpKernel\MapQueryParameter(options: ['min_range' => 1, 'max_range' => 15])] int $limit = 10
    ): Response {
        $queryString = $request->server->get('QUERY_STRING');
        $queries = new UrlQuery($queryString);

        return $this->render('comic/index.html.twig', [
            'rawParameter' => $queryString,
            'paramPage' => $page,
            'paramLimit' => $limit,
            'paramOrderBy' => $queries->all('orderBy', 'orderBys'),
            'resultCount' => $this->comicRepository->countCustom([])
        ]);
    }

    #[Routing\Route('/{code}', name: 'individual')]
    #[HttpKernel\Cache(public: true, maxage: 3600, mustRevalidate: true)]
    public function individual(
        string $code
    ): Response {
        $result = $this->comicRepository->findOneBy(['code' => $code]);
        if (!$result) throw new NotFoundHttpException('Comic not found.');

        return $this->render('comic/individual.html.twig', [
            'paramCode' => $code,
            'result' => $result,
            'funcComicKingApp' => $this->comicKingApp
        ]);
    }

    #[HttpKernel\Cache(public: true, maxage: 900, mustRevalidate: true)]
    public function fragmentList(
        int $limit,
        int $page,
        array | null $orderBy = null
    ): Response {
        $result = $this->comicRepository->findByCustom(
            [],
            \array_map([OrderByDto::class, 'parse'], $orderBy),
            $limit,
            $limit * ($page - 1)
        );

        return $this->render('comic/_list.html.twig', [
            'paramLimit' => $limit,
            'paramPage' => $page,
            'paramOrderBy' => $orderBy,
            'result' => $result,
            'funcComicKingApp' => $this->comicKingApp
        ]);
    }

    #[HttpKernel\Cache(public: true, maxage: 900, mustRevalidate: true)]
    public function fragmentWidget(
        int $limit,
        array | null $orderBy = null
    ): Response {
        $result = $this->comicRepository->findByCustom(
            [],
            \array_map([OrderByDto::class, 'parse'], $orderBy),
            $limit,
            null
        );

        return $this->render('comic/_widget.html.twig', [
            'paramLimit' => $limit,
            'paramOrderBy' => $orderBy,
            'result' => $result,
            'funcComicKingApp' => $this->comicKingApp
        ]);
    }
}

templates/comic/_individual_externals.html.twig
<div class="p-3 border border-2">
    <h2 class="text-center fs-6 pb-2 border-bottom">EXTERNALS</h2>

    {% set comic_externals = funcComicKingApp.comicExternals(result.code) %}
    {% if comic_externals|length > 0 %}
        <div class="row row-cols-1 {{ comic_externals|length > 1 ? 'row-cols-sm-2' : '' }} g-1 m-0">
            {% for external in comic_externals %}
                <div class="col">
                    <a
                        target="_blank"
                        href="{{ funcComicKingApp.href(external.linkWebsiteHost, external.linkRelativeReference) }}"
                        rel="noreferrer nofollow"
                        class="d-block text-truncate text-decoration-none p-2 border"
                    ><img
                        src="{{ funcComicKingApp.href(external.linkWebsiteHost, '/favicon.ico') }}"
                        alt=""
                        style="height: 24px; width: 24px;"
                    /> {{ external.linkWebsiteName }}</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        {{ include('_err.html.twig', { message: 'No External Found' }) }}
    {% endif %}
</div>

templates/comic/_list.html.twig
{% if result %}
    {% set req_langs = app.request.languages|map(l => l|replace({'_': '-'})) %}
    {% set app_langs = funcComicKingApp.languages(null)|map(l => l.lang) %}
    {% set rec_langs = funcComicKingApp.recommendedLangs(app_langs, req_langs) %}

    <style>
        @media (max-width: 415.98px) {
            .list-card {
                --comic-card-h: 192px;
                --comic-card-cover-w: 144px;
                --comic-card-synopsis-h: 124px;
            }
        }
    </style>

    <div class="row row-cols-1 row-cols-lg-2 g-3">
        {% for comic in result %}
            <div class="col list-card">
                {{ include('comic/_list_card.html.twig') }}
            </div>
        {% endfor %}
    </div>
{% else %}
    {{ include('_err.html.twig', { message: 'No Comic Found' }) }}
{% endif %}

templates/comic/_list_card.html.twig
<div class="row m-0 shadow">
    {% set comic_href = path('app_comic_individual', { code: comic.code }) %}
    {% set comic_titles = funcComicKingApp.comicTitles(comic.code, rec_langs, 1) %}
    {% if comic_titles|length > 0 %}
        {% set comic_title = comic_titles[0] %}
    {% endif %}

    <a
        href="{{ comic_href }}"
        class="col p-0 bg-dark"
        style="height: var(--comic-card-h); max-width: var(--comic-card-cover-w);"
    >
        {% set comic_covers = funcComicKingApp.comicCovers(comic.code, [], 1) %}
        {% if comic_covers|length > 0 %}
            {% set comic_cover = funcComicKingApp.image(comic_covers[0].imageULID) %}
        {% else %}
            {% set comic_cover = null %}
        {% endif %}
        <img
            src="{{
                comic_cover
                ? funcComicKingApp.href(comic_cover.linkWebsiteHost, comic_cover.linkRelativeReference)
                : asset('images/comic-cover.jpg')
            }}"
            alt="{{ comic_title.content ?? 'Comic' }} Cover"
            class="w-100 h-100 object-fit-cover"
        />
    </a>

    <div class="col overflow-hidden p-3" style="height: var(--comic-card-h);">
        <a href="{{ comic_href }}" class="text-decoration-none">
            <h5 class="text-truncate pb-2 border-bottom">{{ comic_title.content ?? 'No Title' }}</h5>
        </a>
        <div class="comic-card-synopsis overflow-y-auto" style="height: var(--comic-card-synopsis-h);">
            {% set comic_synopses = funcComicKingApp.comicSynopses(comic.code, [], rec_langs, 1) %}
            {% if comic_synopses|length > 0 %}
                {% set comic_synopsis = comic_synopses[0] %}
            {% endif %}
            {% if comic_synopsis.content ?? false %}
                {{ comic_synopsis.content|markdown_to_html }}
            {% else %}
                {{ '-' }}
            {% endif %}
        </div>
    </div>
</div>

templates/comic/_style.html.twig
<style>
    :root {
        --comic-card-h: 256px;
        --comic-card-cover-w: 192px;
        --comic-card-synopsis-h: 188px;
    }

    .comic-card-synopsis {
        scrollbar-width: thin;
    }

    @media (min-width: 768px) {
        .comic-card {
            height: var(--comic-card-h);
        }

        .comic-card-synopsis {
            height: var(--comic-card-synopsis-h);
        }
    }
</style>

templates/comic/_widget.html.twig
{% set req_langs = app.request.languages|map(l => l|replace({'_': '-'})) %}
{% set app_langs = funcComicKingApp.languages(null)|map(l => l.lang) %}
{% set rec_langs = funcComicKingApp.recommendedLangs(app_langs, req_langs) %}

<div class="d-flex flex-column gap-1">
    {% for comic in result %}
        <a
            href="{{ path('app_comic_individual', { code: comic.code }) }}"
            class="d-flex align-items-center gap-2 text-decoration-none border"
        >
            {% set comic_titles = funcComicKingApp.comicTitles(comic.code, rec_langs, 1) %}
            {% if comic_titles|length > 0 %}
                {% set comic_title = comic_titles[0] %}
            {% else %}
                {% set comic_title = null %}
            {% endif %}

            {% set comic_covers = funcComicKingApp.comicCovers(comic.code, [], 1) %}
            {% if comic_covers|length > 0 %}
                {% set comic_cover = funcComicKingApp.image(comic_covers[0].imageULID) %}
            {% else %}
                {% set comic_cover = null %}
            {% endif %}
            <img
                src="{{
                    comic_cover
                    ? funcComicKingApp.href(comic_cover.linkWebsiteHost, comic_cover.linkRelativeReference)
                    : asset('images/comic-cover.jpg')
                }}"
                alt="{{ comic_title.content ?? 'Comic' }} Cover"
                class="flex-shrink-0 object-fit-cover bg-dark"
                style="height: 64px; width: 48px;"
            />

            <div class="flex-grow-1 overflow-hidden">
                <h2 class="fs-6 text-truncate m-0">{{ comic_title.content ?? 'No Title' }}</h2>
                <small class="link-body-emphasis">{{ comic.createdAt|date('d F Y') }}</small>
            </div>
        </a>
    {% else %}
        {{ include('_err.html.twig', { message: 'No Comic Found' }) }}
    {% endfor %}
</div>

templates/comic/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comics - {{ parent() }}{% endblock %}

{% block main %}
    {{ include('comic/_style.html.twig') }}

    <div class="d-flex flex-column gap-4 p-4">
        <div class="d-flex flex-column">
            <h2 class="align-self-center">Comics</h2>
        </div>

        {{ render(controller('App\\Controller\\ComicController::fragmentList', {
            limit: paramLimit,
            page: paramPage,
            orderBy: paramOrderBy
        })) }}

        {% if resultCount > 0 %}
            <nav class ="">
                <ul class="pagination justify-content-center">
                    {% set rawParameter = rawParameter|replace({
                        ('page=' ~ paramPage): '',
                        ('page=' ~ paramPage ~ '&'): '',
                        ('&page=' ~ paramPage): ''
                    }) %}

                    {% set prevPageNum = paramPage - 1 %}
                    {% set prevPageRef = path('app_comic_index', { page: prevPageNum }) %}
                    {% if rawParameter %}
                        {% set prevPageRef = prevPageRef ~ '&' ~ rawParameter %}
                    {% endif %}
                    {% set prevPageTes = paramPage > 1 %}
                    <li class="page-item{{ prevPageTes ? '' : ' disabled' }}">
                        <a class="page-link" href="{{ prevPageRef }}">Prev</a>
                    </li>

                    <li class="page-item active">
                        <span class="page-link">{{ paramPage }}</span>
                    </li>

                    {% set nextPageNum = paramPage + 1 %}
                    {% set nextPageRef = path('app_comic_index', { page: nextPageNum }) %}
                    {% if rawParameter %}
                        {% set nextPageRef = nextPageRef ~ '&' ~ rawParameter %}
                    {% endif %}
                    {% set nextPageTes = resultCount > paramLimit * paramPage %}
                    <li class="page-item{{ nextPageTes ? '' : ' disabled' }}">
                        <a class="page-link" href="{{ nextPageRef }}">Next</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock %}

templates/comic/individual.html.twig
{% extends 'base.html.twig' %}

{% set req_langs = app.request.languages|map(l => l|replace({'_': '-'})) %}
{% set app_langs = funcComicKingApp.languages(null)|map(l => l.lang) %}
{% set rec_langs = funcComicKingApp.recommendedLangs(app_langs, req_langs) %}

{% set comic_titles = funcComicKingApp.comicTitles(result.code, rec_langs, 1) %}
{% if comic_titles|length > 0 %}
    {% set comic_title = comic_titles[0] %}
{% endif %}

{% block title %}{{ comic_title.content ?? 'Untitled Comic' }} - {{ parent() }}{% endblock %}

{% block main %}
    {{ include('comic/_style.html.twig') }}

    <div class="d-flex flex-column flex-lg-row gap-4 p-4">
        <div class="flex-grow-1 d-flex flex-column gap-3" style="min-width: 0;">
            <div class="d-flex flex-column flex-md-row gap-3 comic-card">
                {% set comic_covers = funcComicKingApp.comicCovers(result.code, [], 1) %}
                {% if comic_covers|length > 0 %}
                    {% set comic_cover = funcComicKingApp.image(comic_covers[0].imageULID) %}
                {% else %}
                    {% set comic_cover = null %}
                {% endif %}
                <img
                    src="{{
                        comic_cover
                        ? funcComicKingApp.href(comic_cover.linkWebsiteHost, comic_cover.linkRelativeReference)
                        : asset('images/comic-cover.jpg')
                    }}"
                    alt="{{ comic_title.content ?? 'Comic' }} Cover"
                    class="flex-shrink-0 align-self-center object-fit-cover shadow bg-dark"
                    style="height: var(--comic-card-h); width: var(--comic-card-cover-w);"
                />

                <div class="flex-grow-1 overflow-hidden p-3 border border-2">
                    <h2 class="fs-5 text-truncate pb-2 border-bottom">{{ comic_title.content ?? 'No Title' }}</h2>
                    <div class="comic-card-synopsis overflow-y-auto">
                        {% set comic_synopses = funcComicKingApp.comicSynopses(result.code, [], rec_langs, 1) %}
                        {% if comic_synopses|length > 0 %}
                            {% set comic_synopsis = comic_synopses[0] %}
                        {% endif %}
                        {% if comic_synopsis.content ?? false %}
                            {{ comic_synopsis.content|markdown_to_html }}
                        {% else %}
                            {{ '-' }}
                        {% endif %}
                    </div>
                </div>
            </div>

            {{ include('comic/_individual_externals.html.twig') }}
        </div>

        <div class="flex-shrink-0 sidebar">
            <div class="p-3 border border-2">
                <h2 class="fs-5 pb-2 border-bottom">⪢ New Comics</h2>
                {{ render_esi(controller('App\\Controller\\ComicController::fragmentWidget', {
                    limit: 4,
                    orderBy: ['createdAt desc']
                })) }}
            </div>
        </div>
    </div>
{% endblock %}